trigger:
- master
- dev
- features/*

pool:
  vmImage: 'vs2017-win2016'

steps:
- task: PowerShell@2
  inputs:
    targetType: filePath
    filePath: ./build.ps1

- task: PublishBuildArtifacts@1
  displayName: 'Publish Nuget Packages to Artifacts'
  inputs:
    PathtoPublish: 'nuget'
    